### PR TITLE
fix: only wait for page and frame targets when connecting

### LINKED ISSUE #2727: fix: only wait for page and frame targets when connecting
[Original issue](https://www.github.com/puppeteer/puppeteer/issues/12888)

### PR DESCRIPTION
**Pull request by kblok**
closes #2727

### CODE REVIEW

File: lib/PuppeteerSharp/Cdp/ChromeTargetManager.cs [hunk 1]
```diff
@@ -103,11 +103,12 @@ private void StoreExistingTargetsForInit()
...
                     _browser.ScreenshotTaskQueue);
 
-                // Targets from extensions and the browser that will not be
-                // auto-attached. Therefore, we should not add them to
-                // #targetsIdsForInit.
-                var skipTarget = kv.Value.Type == TargetType.Browser || kv.Value.Url.StartsWith("chrome-extension://", StringComparison.OrdinalIgnoreCase);
-                if (!skipTarget && (_targetFilterFunc == null || _targetFilterFunc(targetForFilter)))
+                // Only wait for pages and frames (except those from extensions)
+                // to auto-attach.
+                var isPageOrFrame = kv.Value.Type == TargetType.Page || kv.Value.Type == TargetType.IFrame;
```
Comment (jnyrup) [inline lib/PuppeteerSharp/Cdp/ChromeTargetManager.cs:108]:
```suggestion
                var isPageOrFrame = kv.Value.Type is TargetType.Page or TargetType.IFrame;
```
