### PR TITLE
Fix CDP Params could be null

### LINKED ISSUE #2934: Bug: Navigating frame was detached: Connection failed to process System.Byte[]. Nullable object must have a value
Hi guys,

I'm using PuppeteerSharp in combination with the services from Browserless.io.
Regularly my requests fail due to some special CDP messages returned by a (probably modified) Chrome browser. I get the following exception during the `IPage.GoToAsync()` call. That seems to stop every further processing.

**PuppeteerSharp version used:** 20.2.0

Please let me know if you need further information.

**Exception thrown:**
```
System.AggregateException: One or more errors occurred. (Navigating frame was detached: Connection failed to process System.Byte[]. Nullable object must have a value..    at PuppeteerSharp.Cdp.CdpCDPSession.OnMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpCDPSession.cs:line 127
   at PuppeteerSharp.Cdp.Connection.ProcessIncomingMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 339
   at PuppeteerSharp.Cdp.Connection.ProcessMessage(MessageReceivedEventArgs e) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 293)
 ---> PuppeteerSharp.NavigationException: Navigating frame was detached: Connection failed to process System.Byte[]. Nullable object must have a value..    at PuppeteerSharp.Cdp.CdpCDPSession.OnMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpCDPSession.cs:line 127
   at PuppeteerSharp.Cdp.Connection.ProcessIncomingMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 339
   at PuppeteerSharp.Cdp.Connection.ProcessMessage(MessageReceivedEventArgs e) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 293
 ---> PuppeteerSharp.PuppeteerException: Navigating frame was detached: Connection failed to process System.Byte[]. Nullable object must have a value..    at PuppeteerSharp.Cdp.CdpCDPSession.OnMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpCDPSession.cs:line 127
   at PuppeteerSharp.Cdp.Connection.ProcessIncomingMessage(ConnectionResponse obj) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 339
   at PuppeteerSharp.Cdp.Connection.ProcessMessage(MessageReceivedEventArgs e) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/Connection.cs:line 293
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Helpers/TaskHelper.cs:line 106
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Helpers/TaskHelper.cs:line 106
   at PuppeteerSharp.Cdp.CdpFrame.GoToAsync(String url, NavigationOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpFrame.cs:line 102
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Cdp.CdpFrame.GoToAsync(String url, NavigationOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpFrame.cs:line 106
   at DashboardFetcher.BrowserManagement.PageExtensions.GoToAsyncWithOptions(IPage page, String url) in E:\puppeteer\DashboardFetcher\BrowserManagement\BrowserFactory.cs:line 153
   at DashboardFetcher.Fetchers.Fetcher.GetToken(FetcherConfiguration config) in E:\puppeteer\DashboardFetcher\Fetchers\Fetcher.cs:line 212
   at DashboardFetcher.Fetchers.Fetcher.Fetch(FetcherConfiguration config) in E:\puppeteer\DashboardFetcher\Fetchers\Fetcher.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at DashboardFetcher.Commands.FetchAndImportCommand.ProcessSymbol(String symbol) in E:\puppeteer\DashboardFetcher\Commands\FetchAndImportCommand.cs:line 145
```

**I could track down the issue to the following CDP message obtained through Telerik Fiddler:**
`{"method":"Browserless.captchaFound","sessionId":"0291D26408E2E4B2FADF36AA6989ACFC"}`

**I think the following code does not properly handle the case where `obj.Params` is null. Its a nullable type (JsonElement?), thus proper null checks are missing.**
```
CdpCDPSession:
internal void OnMessage(ConnectionResponse obj)
{
    var id = obj.Id;

    if (id.HasValue && _callbacks.TryRemove(id.Value, out var callback))
    {
        Connection.MessageQueue.Enqueue(callback, obj);
    }
    else if (obj.Method != null)
    {
        // If the message was set to not wait for callback, the message won't be in the callbacks dictionary
        // And it might have no method set.
        var method = obj.Method;
        OnMessageReceived(new MessageEventArgs { MessageID = method, MessageData = (JsonElement)obj.Params }); //<-- obj.Params may be null here causing the exception
    }
}
```

### PR DESCRIPTION
**Pull request by kblok**
closes #2934

### CODE REVIEW

File: lib/PuppeteerSharp/Cdp/CdpCDPSession.cs [hunk 1]
```diff
@@ -130,7 +130,7 @@ internal void OnMessage(ConnectionResponse obj)
         {
             Connection.MessageQueue.Enqueue(callback, obj);
         }
-        else if (obj.Method != null)
+        else if (obj.Method is null && obj.Params is not null)
```
Comment (kblok) [inline lib/PuppeteerSharp/Cdp/CdpCDPSession.cs]:
```suggestion
        else if (obj.Method is not null && obj.Params is not null)
```
