### PR TITLE
[Breaking] Replace WebClient with HttpClient

### LINKED ISSUE #1884: HttpClient instead of WebClient
When using PuppeteerSharp with BlazorWASM, i get the following error

`System.PlatformNotSupportedException: System.Net.WebClient is not supported on this platform. Use System.Net.Http.HttpClient instead. at System.Net.WebClient..ctor() at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53`

Is there any plan to update Puppeteer to work use HttpClient instead of WebClient

### PR DESCRIPTION
**Pull request by kblok**
# Description

This will help us support more platforms.

# Breaking change

`BrowserFetcher` is not disposable anymore and it no longer provides a `DownloadProgressChanged` event.

closes #1884

### CODE REVIEW

File: lib/PuppeteerSharp/BrowserFetcher.cs [hunk 1]
```diff
@@ -439,5 +406,23 @@ private async Task UnpackArchiveAsync(string archivePath, string outputPath, str
...
+                handler.UseProxy = true;
+            }
+
+            using var client = new HttpClient(handler);
+
+            // Send the GET request and retrieve the response as a byte array
+            var fileBytes = await client.GetByteArrayAsync(address).ConfigureAwait(false);
+
+            // Write the byte array to a file
+            File.WriteAllBytes(filename, fileBytes);
```
Comment (jnyrup) [inline lib/PuppeteerSharp/BrowserFetcher.cs:425]: To write the data directly to disk instead of having a complete copy in memory
```suggestion
            // Send the GET request and retrieve the response as a stream
            using var downloadStream = await client.GetStreamAsync(address).ConfigureAwait(false);

            // Write the stream to a file
            using var fileStream = File.Create(filename);
            await downloadStream.CopyToAsync(fileStream).ConfigureAwait(false);
```

Comment (kblok) [reply lib/PuppeteerSharp/BrowserFetcher.cs:425]: Thank you!

File: lib/PuppeteerSharp/BrowserFetcher.cs [hunk 2]
```diff
@@ -89,10 +81,16 @@ public async Task<bool> CanDownloadAsync(string revision)
...
+                    handler.Proxy = WebProxy;
+                    handler.UseProxy = true;
+                }
+
+                using var client = new HttpClient(handler);
+                using var requestMessage = new HttpRequestMessage(HttpMethod.Head, url);
+                using var response = await client.SendAsync(requestMessage).ConfigureAwait(false);
                 return response.StatusCode == HttpStatusCode.OK;
             }
             catch (WebException)
```
Comment (novicov) [inline lib/PuppeteerSharp/BrowserFetcher.cs:96]: @kblok  needs to be changed to HttpRequestException

Comment (kblok) [reply lib/PuppeteerSharp/BrowserFetcher.cs:96]: @novicov true

**Comment by AlizerUncaged** [comment]
what the fuck man, what am i supposed to use when ``DownloadProgressChanged `` is gone brah, now i have to update 200 bots manually
