### PR TITLE
Fix: Use Runtime.getProperties for improved performance (#12561)

### LINKED ISSUE #2765: fix(performance): use Runtime.getProperties for improved performance
[Original issue](https://www.github.com/puppeteer/puppeteer/issues/12561)

### PR DESCRIPTION
**Pull request by kblok**
Implements changes from https://github.com/puppeteer/puppeteer/pull/12561

Closes #2765

### CODE REVIEW

File: lib/PuppeteerSharp/ExecutionContext.cs [hunk 1]
```diff
@@ -87,11 +87,10 @@ public async ValueTask DisposeAsync()
...
 
-            if (World != null)
-            {
-                await World.DisposeAsync().ConfigureAwait(false);
-            }
-
+            // Note: We intentionally do NOT dispose World here.
+            // The World owns the ExecutionContext (IsolatedWorld._context),
+            // so IsolatedWorld.DisposeAsync() is responsible for disposing us.
+            // Disposing World here would cause infinite mutual recursion.
```
Comment (kblok) [inline lib/PuppeteerSharp/ExecutionContext.cs]:
```suggestion
```
