### PR TITLE
Fix single file publish

### LINKED ISSUE #2073: Publish using "Produce single file" - Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
### Description

PuppeteerSharp 9.0.0 introduced a bug that will cause to fail the parameterless ctor of BrowserFetcher when using in some published exe with "Produce single file" enabled.

### Complete minimal example reproducing the issue

- Get any example code that uses the parameterless ctor of BrowserFetcher and put it into a console application (.net6 and .net7 are known to cause the issue)
- Publish project with option "Produce single file" enabled.
- Run the published exe
- [Minimal repro](https://github.com/stesee/PuppeteerSharpMinimalRepro)

### Expected behavior:

Running without exception, like PuppeteerSharp 8.

### Actual behavior:

```
Unhandled exception. System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 354
   at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53
   at Program.<Main>$(String[] args) in C:\source\repos\PuppeteerSharpMinimalRepro\PuppeteerSharpMinimalRepro\Program.cs:line 5
   at Program.<Main>(String[] args)
```

### Versions

* Which version of PuppeteerSharp are you using? 9.0.0 and 9.0.1
* Which .NET runtime and version are you targeting? .net6 and .net7

### Additional Information - Workarround - Use overloads of the BrowserFetcher ctor.

```
var options = new BrowserFetcherOptions();
options.Path = Path.GetTempPath();
using var browserFetcher = new BrowserFetcher(options);
var revisionInfo = await browserFetcher.DownloadAsync();
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, ExecutablePath = revisionInfo.ExecutablePath });
await using var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");
await page.ScreenshotAsync("google.jpg");
```

### PR DESCRIPTION
**Pull request by stesee**
closes #2073

### CODE REVIEW

File: lib/PuppeteerSharp.SingleFileDeployment/Program.cs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+using PuppeteerSharp;
```
Comment (kblok) [inline lib/PuppeteerSharp.SingleFileDeployment/Program.cs:1]: Can we call this project `PuppeteerSharp.Tests.SingleFileDeployment`?

File: lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj [hunk 2]
```diff
@@ -14,4 +14,7 @@
     <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
     <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
   </ItemGroup>
+  <Target Name="testCertCheck" BeforeTargets="BeforeBuild" Condition="!Exists('testCert.cer')" >
```
Comment (kblok) [inline lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj:17]: Nice!

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs [hunk 3]
```diff
@@ -0,0 +1,94 @@
+using System.Diagnostics;
+using System.IO;
+using System.Threading.Tasks;
+using Xunit;
+
+namespace PuppeteerSharp.Tests.SingleFileDeployment
+{
+    public class PublishedSelfContainedBinary
```
Comment (kblok) [inline lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs:8]: Let's name this file `PublishedSelfContainedBinary.cs`

**Review by kblok — COMMENTED** [review]
Looking good!

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs (hunk 3 above)
Comment (amaitland) [reply lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs]: SelfContained != SingleFile 

> Publishing your app as self-contained produces an application that includes the .NET runtime and libraries, and your application and its dependencies. Users of the application can run it on a machine that doesn't have the .NET runtime installed.

SelfContained refers to the `runtime` being included with the application. 

> Single-file deployment is available for both the [framework-dependent deployment model](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent) and [self-contained applications](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained).

For reference.

If the intention is to test `Single File` build then one of the following is probably more descript:

- `PublishSingleFileTests`
- `PublishSingleFileDeploymentTests`

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinary.cs [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+            var expectedBinaryPath = Path.Combine(absolutePath, $"bin/Release/net6.0/publish/{projectName}.exe");
+
+            DeleteIfExists(expectedBinaryPath);
+
+            using var process = new Process
+            {
+                StartInfo = new ProcessStartInfo
+                {
+                    FileName = "dotnet",
+                    Arguments = $"publish {absolutePath} --configuration Release -f net6.0 -p:PublishProfile=FolderProfile",
```
Comment (amaitland) [inline lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinary.cs:66]: I don't see a [FolderProfile.pubxml](https://github.com/stesee/PuppeteerSharpMinimalRepro/blob/master/PuppeteerSharpMinimalRepro/Properties/PublishProfiles/FolderProfile.pubxml) file in this `PR`. Am I missing something?

For simplicity is it better to just include the args here directly?

```
-r win-x64 -p:PublishSingleFile=true --self-contained false
```

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/FactRunableOnWindowsAttribute.cs [hunk 5]
```diff
@@ -0,0 +1,18 @@
+using System.Runtime.InteropServices;
+using Xunit;
+
+namespace PuppeteerSharp.Tests.SingleFileDeployment
+{
+    internal class FactRunableOnWindowsAttribute : FactAttribute
```
Comment (amaitland) [inline lib/PuppeteerSharp.Tests/SingleFileDeployment/FactRunableOnWindowsAttribute.cs:6]: There's other `xunit` test attributes in https://github.com/hardkoded/puppeteer-sharp/tree/master/lib/PuppeteerSharp.Tests/Attributes

Should this live in there?

File: lib/PuppeteerSharp/BrowserFetcher.cs [hunk 6]
```diff
@@ -348,25 +354,29 @@ internal static Platform GetCurrentPlatform()
         internal static string GetExecutablePath()
         {
             DirectoryInfo assemblyDirectory = new(AppContext.BaseDirectory);
-            if (!assemblyDirectory.Exists || !File.Exists(Path.Combine(assemblyDirectory.FullName, "PuppeteerSharp.dll")))
+            if (!assemblyDirectory.Exists || !File.Exists(Path.Combine(assemblyDirectory.FullName, nameof(Puppeteer) + ".dll")))
```
Comment (amaitland) [inline lib/PuppeteerSharp/BrowserFetcher.cs:357]: Can you double check that `nameof(Puppeteer)` is equal to `PuppeteerSharp`? I think this check will always fail with this change.

Getting the name of the assembly from the actual assembly would be better.  Possibly something like the following?

```c#
var assembly = typeof(Puppeteer).Assembly;
var assemblyName = assembly.GetName().Name;
```

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinary.cs (hunk 4 above)
Comment (amaitland) [reply lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinary.cs:66]: `--use-current-runtime` instead of specifying a `RID` would actually be preferable.

Make it easer to take this test cross platform

File: lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs (hunk 3 above)
Comment (stesee) [reply lib/PuppeteerSharp.Tests/SingleFileDeployment/PublishedSelfContainedBinaryShouldWork.cs]: I choosed 'PublishSingleFileTests'

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+            }
+
+            Assert.True(isExited);
+
+            Assert.True(File.Exists(actualFilePath), $"StdOut: {outputResult}\nStdErr: {errorResult}\n");
+        }
+
+        private static string GetStreamOutput(StreamReader stream)
+        {
+            var outputReadTask = Task.Run(() => stream.ReadToEnd());
```
Comment (kblok) [inline lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: Why do we need this `Task.Run`?

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+
+            return outputReadTask.Result;
+        }
+
+        private static string DotnetPublishSingleFile(string projectName)
+        {
+            var absolutePath = Path.GetFullPath("../../../../" + projectName);
```
Comment (kblok) [inline lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:57]: Let's use `Path.Join` here.

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+            var expectedBinaryPath = Path.Combine(absolutePath, $"bin/Release/net6.0/win-x64/publish/{projectName}.exe");
```
Comment (kblok) [inline lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:58]: Can we add a comment making sure that  `net6.0` is in sync with the project file?

**Comment by kblok** [comment]
@amaitland as you stepped into this, I'll wait for your approval.

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 7 above)
Comment (stesee) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: I followed https://stackoverflow.com/questions/7160187/standardoutput-readtoend-hangs

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 8 above)
Comment (stesee) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:57]: There is no Path.Join in net48. Used Path.Combine.

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 9 above)
Comment (stesee) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:58]: Solved that using `publish -o ./publish`

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 7 above)
Comment (amaitland) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: Does using [ReadToEndAsync](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.readtoendasync?view=net-7.0) work around the issue?

Comment (stesee) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: I will give it a try... I am not sure optimizing testcode is worth it... 😌

File: lib/PuppeteerSharp/BrowserFetcher.cs [hunk 10]
```diff
@@ -347,26 +353,29 @@ internal static Platform GetCurrentPlatform()
...
-                {
-                    assemblyLocation = codeBase.LocalPath;
-                }
-                else
+                var assemblyLocation = assembly.Location;
+
+                if (string.IsNullOrEmpty(assemblyLocation))
                 {
-                    assemblyLocation = assembly.Location;
+                    var singleFilePublishFilePathForBrowserExecutables = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), nameof(Puppeteer));
```
Comment (amaitland) [inline lib/PuppeteerSharp/BrowserFetcher.cs:366]: Should the folder name be `PuppeteerSharp`? 

Thoughts?

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+            var expectedBinaryPath = Path.Combine(absolutePath, $"publish/{projectName}.exe");
+
+            DeleteIfExists(expectedBinaryPath);
+
+            using var process = new Process
+            {
+                StartInfo = new ProcessStartInfo
+                {
+                    FileName = "dotnet",
+                    Arguments = $"publish {absolutePath} --configuration Release -r win-x64 -p:PublishSingleFile=true --self-contained false --use-current-runtime -o ./publish",
```
Comment (amaitland) [inline lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:67]: If you remove `-r win-x64` then hopefully `--use-current-runtime` should pickup the current `RID`.

https://github.com/dotnet/sdk/issues/10449

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 7 above)
Comment (amaitland) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: I'll defer to @kblok on this one, what's your thoughts?

File: lib/PuppeteerSharp/BrowserFetcher.cs (hunk 10 above)
Comment (stesee) [reply lib/PuppeteerSharp/BrowserFetcher.cs:366]: There are a bunch of aspects:
- it is common to use the vendor name for the folder - techies will know what to expect in `PuppeteerSharp`
- shared use of downloaded chrome in multiple puppeteer-sharp consumers - for good or bad
- length vs max path length
- complexity to do magic to get the name out of consuming applications

I would like to keep it simple.

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 7 above)
Comment (stesee) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: As far as I remember reading StdOut and StdErr at the same time is causing deadlocks and using [ReadToEndAsync](https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.readtoendasync?view=net-7.0) wont fix that. The output of them isnt used to assert the expectation and could be dropped entirely but if the assertion will fail it is the information you will need to find out what went wrong.

File: lib/PuppeteerSharp/BrowserFetcher.cs (hunk 10 above)
Comment (amaitland) [reply lib/PuppeteerSharp/BrowserFetcher.cs:366]: Unless I'm mistaken here `nameof(Puppeteer)` = `Puppeteer` 

I think the folder should be named `PuppeteerSharp`.

> I would like to keep it simple.

You've gone way more complex than I was actually meaning 😄

File: lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs (hunk 7 above)
Comment (amaitland) [reply lib/PuppeteerSharp.Tests/PublishSingleFileTests/PublishSingleFileTests.cs:50]: I've seen the following pattern used a few times, I've not used it myself yet.

https://stackoverflow.com/a/53504707/4583726

**Comment by amaitland** [comment]
@kblok Just ran the latest changes locally, happy to approve for merge 👍
