### PR TITLE
Fix BoundingBox equality

### LINKED ISSUE #1626: BoundingBox Equals has a null bug
```
        public override bool Equals(object obj)
        {
            if (obj == null && GetType() != obj.GetType())
            {
                return false;
            }

            return Equals((BoundingBox)obj);
        }
```

if `obj == null` is true, `obj.GetType()` will throw

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #1626

### CODE REVIEW

File: lib/PuppeteerSharp/BoundingBox.cs [hunk 1]
```diff
@@ -66,7 +66,7 @@ internal Clip ToClip()
         /// <inheritdoc/>
         public override bool Equals(object obj)
         {
-            if (obj == null && GetType() != obj.GetType())
+            if (obj == null || GetType() != obj.GetType())
```
Comment (kblok) [inline lib/PuppeteerSharp/BoundingBox.cs:69]: :O

**Review by kblok — APPROVED** [review]

**Comment by Androbin** [comment]
I can't reproduce this issue locally, seems to be a flake, an interesting one though:
https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/38258335/job/74y3bkkee23q45ri#L86
